### ISSUE TITLE
my gradle project can't sync

### ISSUE THREAD

**Issue by letroll** [yoavst/androidKotlin#1]
Hello, I have read the instructions, put 
‘‘‘
repositories {
        maven {
            url "https://jitpack.io"
        }
    }
‘‘‘
and
‘‘‘
compile 'com.github.yoavst:androidKotlin:1.0.2'
‘‘‘

in my script but that don't work, can you help me?

**Comment by yoavst** [comment]
Yes, use 1.0.3 for newest kotlin version

**Comment by letroll** [comment]
thank you very much to trying to help me but it's not ok :
 Failed to resolve: com.github.yoavst:androidKotlin:1.0.3

**Comment by yoavst** [comment]
try     

``` groovy
compile 'com.github.yoavst:androidKotlin:v1.0.3'
```

**Comment by letroll** [comment]
sorry but it's not working for me, with:
compile 'com.github.yoavst:androidKotlin:1.0.1'
compile 'com.github.yoavst:androidKotlin:1.0.2'
compile 'com.github.yoavst:androidKotlin:1.0.3'
or
compile 'com.github.yoavst:androidKotlin:v1.0.3'

nothing

my build.gralde:
‘‘‘
buildscript {
    ext.kotlin_version = '0.11.91'
    repositories {
        mavenCentral()
        maven {
            url "https://jitpack.io"
        }
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion 21
    buildToolsVersion "22"

```
defaultConfig {
    applicationId "fr.letroll.test"
    minSdkVersion 16
    targetSdkVersion 21
    versionCode 1
    versionName "1.0"
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}

sourceSets {
    main.java.srcDirs += 'src/main/kotlin'
}
```

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22'
    compile 'com.github.yoavst:androidKotlin:v1.0.3'
    compile 'org.slf4j:slf4j-api:1.7.7'
    compile 'com.github.tony19:logback-android-classic:1.1.1-3'
    compile 'de.hdodenhof:circleimageview:1.1.0'
    compile 'uk.co.chrisjenx:calligraphy:2.0.1'
    compile 'com.google.code.gson:gson:2.2.4'
    compile 'com.jakewharton:butterknife:5.1.2'
    compile 'com.googlecode.android-query:android-query:0.25.9'
    compile 'com.squareup.dagger:dagger:1.2.0'
    provided 'com.squareup.dagger:dagger-compiler:1.2.0'
    //    compile 'org.apache.commons:commons-collections4:4.0'
    compile 'com.squareup.retrofit:retrofit:1.6.1'
    compile 'com.squareup.picasso:picasso:2.3.2'
    compile 'com.squareup:otto:1.3.4'
    compile 'net.danlew:android.joda:2.5.0'
    compile 'com.netflix.rxjava:rxjava-core:0.17.1'
    compile 'com.netflix.rxjava:rxjava-android:0.17.1'
    compile 'com.squareup.okhttp:okhttp:2.0.0'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.0.0'
    compile('com.mikepenz.materialdrawer:library:2.5.4@aar') {
        transitive = true
    }
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    compile 'org.jsoup:jsoup:1.8.1'
}
‘‘‘

And I'm on Android Studio 1.1.0

**Comment by letroll** [comment]
Sorry for that, I didn't understant than 
‘‘‘
repositories {
    maven {
        url "https://jitpack.io"
    }
}
‘‘‘

need to be at the build.gradle's root.

Now It's working
